CREATE USER DESENV
IDENTIFIED BY DESENV
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

alter session set "_ORACLE_SCRIPT"=TRUE;-- was necessary because the command, create user, wasn't working

 
